/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as ConsultorioRouteImport } from './routes/consultorio'
import { Route as AreaRouteImport } from './routes/$area'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as ConsultorioIndexRouteImport } from './routes/consultorio.index'
import { Route as GestaoPromptsRouteImport } from './routes/gestao.prompts'
import { Route as ConsultorioFichaPlanejamentoRouteImport } from './routes/consultorio.ficha-planejamento'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'

const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioRoute = ConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoRoute,
} as any)
const ConsultorioIndexRoute = ConsultorioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultorioRoute,
} as any)
const GestaoPromptsRoute = GestaoPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => GestaoRoute,
} as any)
const ConsultorioFichaPlanejamentoRoute =
  ConsultorioFichaPlanejamentoRouteImport.update({
    id: '/ficha-planejamento',
    path: '/ficha-planejamento',
    getParentRoute: () => ConsultorioRoute,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$area': typeof AreaRoute
  '/consultorio': typeof ConsultorioRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/consultorio/': typeof ConsultorioIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$area': typeof AreaRoute
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/consultorio': typeof ConsultorioIndexRoute
  '/gestao': typeof GestaoIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$area': typeof AreaRoute
  '/consultorio': typeof ConsultorioRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/consultorio/': typeof ConsultorioIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$area'
    | '/consultorio'
    | '/gestao'
    | '/consultorio/ficha-planejamento'
    | '/gestao/prompts'
    | '/consultorio/'
    | '/gestao/'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$area'
    | '/consultorio/ficha-planejamento'
    | '/gestao/prompts'
    | '/consultorio'
    | '/gestao'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/$area'
    | '/consultorio'
    | '/gestao'
    | '/consultorio/ficha-planejamento'
    | '/gestao/prompts'
    | '/consultorio/'
    | '/gestao/'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRoute: typeof AreaRoute
  ConsultorioRoute: typeof ConsultorioRouteWithChildren
  GestaoRoute: typeof GestaoRouteWithChildren
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio': {
      id: '/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof ConsultorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$area': {
      id: '/$area'
      path: '/$area'
      fullPath: '/$area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/consultorio/': {
      id: '/consultorio/'
      path: '/'
      fullPath: '/consultorio/'
      preLoaderRoute: typeof ConsultorioIndexRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/gestao/prompts': {
      id: '/gestao/prompts'
      path: '/prompts'
      fullPath: '/gestao/prompts'
      preLoaderRoute: typeof GestaoPromptsRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/consultorio/ficha-planejamento': {
      id: '/consultorio/ficha-planejamento'
      path: '/ficha-planejamento'
      fullPath: '/consultorio/ficha-planejamento'
      preLoaderRoute: typeof ConsultorioFichaPlanejamentoRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsultorioRouteChildren {
  ConsultorioFichaPlanejamentoRoute: typeof ConsultorioFichaPlanejamentoRoute
  ConsultorioIndexRoute: typeof ConsultorioIndexRoute
}

const ConsultorioRouteChildren: ConsultorioRouteChildren = {
  ConsultorioFichaPlanejamentoRoute: ConsultorioFichaPlanejamentoRoute,
  ConsultorioIndexRoute: ConsultorioIndexRoute,
}

const ConsultorioRouteWithChildren = ConsultorioRoute._addFileChildren(
  ConsultorioRouteChildren,
)

interface GestaoRouteChildren {
  GestaoPromptsRoute: typeof GestaoPromptsRoute
  GestaoIndexRoute: typeof GestaoIndexRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoPromptsRoute: GestaoPromptsRoute,
  GestaoIndexRoute: GestaoIndexRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRoute: AreaRoute,
  ConsultorioRoute: ConsultorioRouteWithChildren,
  GestaoRoute: GestaoRouteWithChildren,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
