/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EnvioEmLoteRouteImport } from './routes/envio-em-lote'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultorioRouteImport } from './routes/consultorio'
import { Route as AreaRouteImport } from './routes/$area'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestaoIndexRouteImport } from './routes/gestao.index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as ConsultorioIndexRouteImport } from './routes/consultorio.index'
import { Route as AreaIndexRouteImport } from './routes/$area.index'
import { Route as GestaoTarefasRecorrentesMensalRouteImport } from './routes/gestao.tarefas-recorrentes-mensal'
import { Route as GestaoTarefasRecorrentesRouteImport } from './routes/gestao.tarefas-recorrentes'
import { Route as GestaoRotinaRouteImport } from './routes/gestao.rotina'
import { Route as GestaoPromptsRouteImport } from './routes/gestao.prompts'
import { Route as GestaoLinksRouteImport } from './routes/gestao.links'
import { Route as FinanceiroPagamentosRecorrentesRouteImport } from './routes/financeiro.pagamentos-recorrentes'
import { Route as FinanceiroLinksRouteImport } from './routes/financeiro.links'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as ConsultorioProtocolosRouteImport } from './routes/consultorio.protocolos'
import { Route as ConsultorioModelosDocumentosRouteImport } from './routes/consultorio.modelos-documentos'
import { Route as ConsultorioLinksRouteImport } from './routes/consultorio.links'
import { Route as ConsultorioFichaPlanejamentoRouteImport } from './routes/consultorio.ficha-planejamento'
import { Route as AreaLinksRouteImport } from './routes/$area.links'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksResumoDiarioTarefasRouteImport } from './routes/api/public/hooks/resumo-diario-tarefas'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvioEmLoteRoute = EnvioEmLoteRouteImport.update({
  id: '/envio-em-lote',
  path: '/envio-em-lote',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioRoute = ConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoIndexRoute = GestaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestaoRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ConsultorioIndexRoute = ConsultorioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsultorioRoute,
} as any)
const AreaIndexRoute = AreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreaRoute,
} as any)
const GestaoTarefasRecorrentesMensalRoute =
  GestaoTarefasRecorrentesMensalRouteImport.update({
    id: '/tarefas-recorrentes-mensal',
    path: '/tarefas-recorrentes-mensal',
    getParentRoute: () => GestaoRoute,
  } as any)
const GestaoTarefasRecorrentesRoute =
  GestaoTarefasRecorrentesRouteImport.update({
    id: '/tarefas-recorrentes',
    path: '/tarefas-recorrentes',
    getParentRoute: () => GestaoRoute,
  } as any)
const GestaoRotinaRoute = GestaoRotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoPromptsRoute = GestaoPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => GestaoRoute,
} as any)
const GestaoLinksRoute = GestaoLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => GestaoRoute,
} as any)
const FinanceiroPagamentosRecorrentesRoute =
  FinanceiroPagamentosRecorrentesRouteImport.update({
    id: '/pagamentos-recorrentes',
    path: '/pagamentos-recorrentes',
    getParentRoute: () => FinanceiroRoute,
  } as any)
const FinanceiroLinksRoute = FinanceiroLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioProtocolosRoute = ConsultorioProtocolosRouteImport.update({
  id: '/protocolos',
  path: '/protocolos',
  getParentRoute: () => ConsultorioRoute,
} as any)
const ConsultorioModelosDocumentosRoute =
  ConsultorioModelosDocumentosRouteImport.update({
    id: '/modelos-documentos',
    path: '/modelos-documentos',
    getParentRoute: () => ConsultorioRoute,
  } as any)
const ConsultorioLinksRoute = ConsultorioLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => ConsultorioRoute,
} as any)
const ConsultorioFichaPlanejamentoRoute =
  ConsultorioFichaPlanejamentoRouteImport.update({
    id: '/ficha-planejamento',
    path: '/ficha-planejamento',
    getParentRoute: () => ConsultorioRoute,
  } as any)
const AreaLinksRoute = AreaLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AreaRoute,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResumoDiarioTarefasRoute =
  ApiPublicHooksResumoDiarioTarefasRouteImport.update({
    id: '/api/public/hooks/resumo-diario-tarefas',
    path: '/api/public/hooks/resumo-diario-tarefas',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$area': typeof AreaRouteWithChildren
  '/consultorio': typeof ConsultorioRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/envio-em-lote': typeof EnvioEmLoteRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/$area/links': typeof AreaLinksRoute
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/consultorio/links': typeof ConsultorioLinksRoute
  '/consultorio/modelos-documentos': typeof ConsultorioModelosDocumentosRoute
  '/consultorio/protocolos': typeof ConsultorioProtocolosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/links': typeof FinanceiroLinksRoute
  '/financeiro/pagamentos-recorrentes': typeof FinanceiroPagamentosRecorrentesRoute
  '/gestao/links': typeof GestaoLinksRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/gestao/rotina': typeof GestaoRotinaRoute
  '/gestao/tarefas-recorrentes': typeof GestaoTarefasRecorrentesRoute
  '/gestao/tarefas-recorrentes-mensal': typeof GestaoTarefasRecorrentesMensalRoute
  '/$area/': typeof AreaIndexRoute
  '/consultorio/': typeof ConsultorioIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/api/public/hooks/resumo-diario-tarefas': typeof ApiPublicHooksResumoDiarioTarefasRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/envio-em-lote': typeof EnvioEmLoteRoute
  '/unlock': typeof UnlockRoute
  '/$area/links': typeof AreaLinksRoute
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/consultorio/links': typeof ConsultorioLinksRoute
  '/consultorio/modelos-documentos': typeof ConsultorioModelosDocumentosRoute
  '/consultorio/protocolos': typeof ConsultorioProtocolosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/links': typeof FinanceiroLinksRoute
  '/financeiro/pagamentos-recorrentes': typeof FinanceiroPagamentosRecorrentesRoute
  '/gestao/links': typeof GestaoLinksRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/gestao/rotina': typeof GestaoRotinaRoute
  '/gestao/tarefas-recorrentes': typeof GestaoTarefasRecorrentesRoute
  '/gestao/tarefas-recorrentes-mensal': typeof GestaoTarefasRecorrentesMensalRoute
  '/$area': typeof AreaIndexRoute
  '/consultorio': typeof ConsultorioIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/gestao': typeof GestaoIndexRoute
  '/api/public/hooks/resumo-diario-tarefas': typeof ApiPublicHooksResumoDiarioTarefasRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$area': typeof AreaRouteWithChildren
  '/consultorio': typeof ConsultorioRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/envio-em-lote': typeof EnvioEmLoteRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/gestao': typeof GestaoRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/$area/links': typeof AreaLinksRoute
  '/consultorio/ficha-planejamento': typeof ConsultorioFichaPlanejamentoRoute
  '/consultorio/links': typeof ConsultorioLinksRoute
  '/consultorio/modelos-documentos': typeof ConsultorioModelosDocumentosRoute
  '/consultorio/protocolos': typeof ConsultorioProtocolosRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/links': typeof FinanceiroLinksRoute
  '/financeiro/pagamentos-recorrentes': typeof FinanceiroPagamentosRecorrentesRoute
  '/gestao/links': typeof GestaoLinksRoute
  '/gestao/prompts': typeof GestaoPromptsRoute
  '/gestao/rotina': typeof GestaoRotinaRoute
  '/gestao/tarefas-recorrentes': typeof GestaoTarefasRecorrentesRoute
  '/gestao/tarefas-recorrentes-mensal': typeof GestaoTarefasRecorrentesMensalRoute
  '/$area/': typeof AreaIndexRoute
  '/consultorio/': typeof ConsultorioIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/gestao/': typeof GestaoIndexRoute
  '/api/public/hooks/resumo-diario-tarefas': typeof ApiPublicHooksResumoDiarioTarefasRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$area'
    | '/consultorio'
    | '/dashboard'
    | '/envio-em-lote'
    | '/financeiro'
    | '/gestao'
    | '/unlock'
    | '/$area/links'
    | '/consultorio/ficha-planejamento'
    | '/consultorio/links'
    | '/consultorio/modelos-documentos'
    | '/consultorio/protocolos'
    | '/convite/$token'
    | '/financeiro/links'
    | '/financeiro/pagamentos-recorrentes'
    | '/gestao/links'
    | '/gestao/prompts'
    | '/gestao/rotina'
    | '/gestao/tarefas-recorrentes'
    | '/gestao/tarefas-recorrentes-mensal'
    | '/$area/'
    | '/consultorio/'
    | '/financeiro/'
    | '/gestao/'
    | '/api/public/hooks/resumo-diario-tarefas'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/envio-em-lote'
    | '/unlock'
    | '/$area/links'
    | '/consultorio/ficha-planejamento'
    | '/consultorio/links'
    | '/consultorio/modelos-documentos'
    | '/consultorio/protocolos'
    | '/convite/$token'
    | '/financeiro/links'
    | '/financeiro/pagamentos-recorrentes'
    | '/gestao/links'
    | '/gestao/prompts'
    | '/gestao/rotina'
    | '/gestao/tarefas-recorrentes'
    | '/gestao/tarefas-recorrentes-mensal'
    | '/$area'
    | '/consultorio'
    | '/financeiro'
    | '/gestao'
    | '/api/public/hooks/resumo-diario-tarefas'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/$area'
    | '/consultorio'
    | '/dashboard'
    | '/envio-em-lote'
    | '/financeiro'
    | '/gestao'
    | '/unlock'
    | '/$area/links'
    | '/consultorio/ficha-planejamento'
    | '/consultorio/links'
    | '/consultorio/modelos-documentos'
    | '/consultorio/protocolos'
    | '/convite/$token'
    | '/financeiro/links'
    | '/financeiro/pagamentos-recorrentes'
    | '/gestao/links'
    | '/gestao/prompts'
    | '/gestao/rotina'
    | '/gestao/tarefas-recorrentes'
    | '/gestao/tarefas-recorrentes-mensal'
    | '/$area/'
    | '/consultorio/'
    | '/financeiro/'
    | '/gestao/'
    | '/api/public/hooks/resumo-diario-tarefas'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRoute: typeof AreaRouteWithChildren
  ConsultorioRoute: typeof ConsultorioRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EnvioEmLoteRoute: typeof EnvioEmLoteRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  GestaoRoute: typeof GestaoRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiPublicHooksResumoDiarioTarefasRoute: typeof ApiPublicHooksResumoDiarioTarefasRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envio-em-lote': {
      id: '/envio-em-lote'
      path: '/envio-em-lote'
      fullPath: '/envio-em-lote'
      preLoaderRoute: typeof EnvioEmLoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio': {
      id: '/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof ConsultorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$area': {
      id: '/$area'
      path: '/$area'
      fullPath: '/$area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/': {
      id: '/gestao/'
      path: '/'
      fullPath: '/gestao/'
      preLoaderRoute: typeof GestaoIndexRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/consultorio/': {
      id: '/consultorio/'
      path: '/'
      fullPath: '/consultorio/'
      preLoaderRoute: typeof ConsultorioIndexRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/$area/': {
      id: '/$area/'
      path: '/'
      fullPath: '/$area/'
      preLoaderRoute: typeof AreaIndexRouteImport
      parentRoute: typeof AreaRoute
    }
    '/gestao/tarefas-recorrentes-mensal': {
      id: '/gestao/tarefas-recorrentes-mensal'
      path: '/tarefas-recorrentes-mensal'
      fullPath: '/gestao/tarefas-recorrentes-mensal'
      preLoaderRoute: typeof GestaoTarefasRecorrentesMensalRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/tarefas-recorrentes': {
      id: '/gestao/tarefas-recorrentes'
      path: '/tarefas-recorrentes'
      fullPath: '/gestao/tarefas-recorrentes'
      preLoaderRoute: typeof GestaoTarefasRecorrentesRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/rotina': {
      id: '/gestao/rotina'
      path: '/rotina'
      fullPath: '/gestao/rotina'
      preLoaderRoute: typeof GestaoRotinaRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/prompts': {
      id: '/gestao/prompts'
      path: '/prompts'
      fullPath: '/gestao/prompts'
      preLoaderRoute: typeof GestaoPromptsRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/gestao/links': {
      id: '/gestao/links'
      path: '/links'
      fullPath: '/gestao/links'
      preLoaderRoute: typeof GestaoLinksRouteImport
      parentRoute: typeof GestaoRoute
    }
    '/financeiro/pagamentos-recorrentes': {
      id: '/financeiro/pagamentos-recorrentes'
      path: '/pagamentos-recorrentes'
      fullPath: '/financeiro/pagamentos-recorrentes'
      preLoaderRoute: typeof FinanceiroPagamentosRecorrentesRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/links': {
      id: '/financeiro/links'
      path: '/links'
      fullPath: '/financeiro/links'
      preLoaderRoute: typeof FinanceiroLinksRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio/protocolos': {
      id: '/consultorio/protocolos'
      path: '/protocolos'
      fullPath: '/consultorio/protocolos'
      preLoaderRoute: typeof ConsultorioProtocolosRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/consultorio/modelos-documentos': {
      id: '/consultorio/modelos-documentos'
      path: '/modelos-documentos'
      fullPath: '/consultorio/modelos-documentos'
      preLoaderRoute: typeof ConsultorioModelosDocumentosRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/consultorio/links': {
      id: '/consultorio/links'
      path: '/links'
      fullPath: '/consultorio/links'
      preLoaderRoute: typeof ConsultorioLinksRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/consultorio/ficha-planejamento': {
      id: '/consultorio/ficha-planejamento'
      path: '/ficha-planejamento'
      fullPath: '/consultorio/ficha-planejamento'
      preLoaderRoute: typeof ConsultorioFichaPlanejamentoRouteImport
      parentRoute: typeof ConsultorioRoute
    }
    '/$area/links': {
      id: '/$area/links'
      path: '/links'
      fullPath: '/$area/links'
      preLoaderRoute: typeof AreaLinksRouteImport
      parentRoute: typeof AreaRoute
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resumo-diario-tarefas': {
      id: '/api/public/hooks/resumo-diario-tarefas'
      path: '/api/public/hooks/resumo-diario-tarefas'
      fullPath: '/api/public/hooks/resumo-diario-tarefas'
      preLoaderRoute: typeof ApiPublicHooksResumoDiarioTarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AreaRouteChildren {
  AreaLinksRoute: typeof AreaLinksRoute
  AreaIndexRoute: typeof AreaIndexRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaLinksRoute: AreaLinksRoute,
  AreaIndexRoute: AreaIndexRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

interface ConsultorioRouteChildren {
  ConsultorioFichaPlanejamentoRoute: typeof ConsultorioFichaPlanejamentoRoute
  ConsultorioLinksRoute: typeof ConsultorioLinksRoute
  ConsultorioModelosDocumentosRoute: typeof ConsultorioModelosDocumentosRoute
  ConsultorioProtocolosRoute: typeof ConsultorioProtocolosRoute
  ConsultorioIndexRoute: typeof ConsultorioIndexRoute
}

const ConsultorioRouteChildren: ConsultorioRouteChildren = {
  ConsultorioFichaPlanejamentoRoute: ConsultorioFichaPlanejamentoRoute,
  ConsultorioLinksRoute: ConsultorioLinksRoute,
  ConsultorioModelosDocumentosRoute: ConsultorioModelosDocumentosRoute,
  ConsultorioProtocolosRoute: ConsultorioProtocolosRoute,
  ConsultorioIndexRoute: ConsultorioIndexRoute,
}

const ConsultorioRouteWithChildren = ConsultorioRoute._addFileChildren(
  ConsultorioRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroLinksRoute: typeof FinanceiroLinksRoute
  FinanceiroPagamentosRecorrentesRoute: typeof FinanceiroPagamentosRecorrentesRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroLinksRoute: FinanceiroLinksRoute,
  FinanceiroPagamentosRecorrentesRoute: FinanceiroPagamentosRecorrentesRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface GestaoRouteChildren {
  GestaoLinksRoute: typeof GestaoLinksRoute
  GestaoPromptsRoute: typeof GestaoPromptsRoute
  GestaoRotinaRoute: typeof GestaoRotinaRoute
  GestaoTarefasRecorrentesRoute: typeof GestaoTarefasRecorrentesRoute
  GestaoTarefasRecorrentesMensalRoute: typeof GestaoTarefasRecorrentesMensalRoute
  GestaoIndexRoute: typeof GestaoIndexRoute
}

const GestaoRouteChildren: GestaoRouteChildren = {
  GestaoLinksRoute: GestaoLinksRoute,
  GestaoPromptsRoute: GestaoPromptsRoute,
  GestaoRotinaRoute: GestaoRotinaRoute,
  GestaoTarefasRecorrentesRoute: GestaoTarefasRecorrentesRoute,
  GestaoTarefasRecorrentesMensalRoute: GestaoTarefasRecorrentesMensalRoute,
  GestaoIndexRoute: GestaoIndexRoute,
}

const GestaoRouteWithChildren =
  GestaoRoute._addFileChildren(GestaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRoute: AreaRouteWithChildren,
  ConsultorioRoute: ConsultorioRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EnvioEmLoteRoute: EnvioEmLoteRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  GestaoRoute: GestaoRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiPublicHooksResumoDiarioTarefasRoute:
    ApiPublicHooksResumoDiarioTarefasRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
